use_frameworks!

platform :ios, '11.0'

target 'XJHWKWebInterceptorKit_Example' do
  pod 'XJHWKWebInterceptorKit', :path => '../'
  
  pod 'XJHNetworkInterceptorKit'
  
  pod 'Masonry'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'XJHViewState'

  target 'XJHWKWebInterceptorKit_Tests' do
    inherit! :search_paths

    
  end
end
